### PR TITLE
Fix typo in comment

### PR DESCRIPTION
**Pull request by ryandesign**

### CODE REVIEW

**Review by rbdannenberg — COMMENTED** [review]
We had a recent exchange about whether Makefile.osx should even be here (was that you? sorry I don't remember). Are you using Makefile.osx instead of cmake? Maybe a better fix is to remove Makefile.osx. I can't remember why it was created.

**Comment by ryandesign** [comment]
It was me. I don't use Makefile.osx but others evidently use it. ([Homebrew does](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/portmidi.rb); don't know why.) Not wanting to be the one to decide to remove it, I wanted to submit a fix for this typo, and may submit a fix to install the pkg-config file as well.

**Comment by rbdannenberg** [comment]
I started a discussion on Homebrew, so we'll see if anyone answers. If you submit a "fix to install the pkg-config file" it should also add a discussion of why anyone would use Makefile.osx and what it does. If it does nothing different from cmake, then it should be replace by a simple invocation of cmake, make, etc.  Cmake already has a bunch of install code that I don't understand (nor do I really want to), which is OK as long as it's there because someone wants it bad enough to write it, use it, and fix it. On the other hand, Makefile.osx seems to be a left-over from many years ago, and probably is only used by Homebrew because it was there by mistake. If it's a mistake, let's don't propagate it.

**Comment by rbdannenberg** [comment]
As soon as I pressed "Comment," I had second thoughts: I really appreciate your efforts and interest, so don't take it the wrong way!

**Pull request merged**
